const Sequelize = require('sequelize');

module.exports = {
  "Games Played": Sequelize.INTEGER,
  "Passing Attempts": Sequelize.INTEGER,
  "Completions": Sequelize.INTEGER,
  "Incomplete Passes": Sequelize.INTEGER,
  "Passing Yards": Sequelize.INTEGER,
  "Passing Touchdowns": Sequelize.INTEGER,
  "Interceptions": Sequelize.INTEGER,
  "Sacks": Sequelize.INTEGER,
  "Rushing Attempts": Sequelize.INTEGER,
  "Rushing Yards": Sequelize.INTEGER,
  "Rushing Touchdowns": Sequelize.INTEGER,
  "Receptions": Sequelize.INTEGER,
  "Receiving Yards": Sequelize.INTEGER,
  "Receiving Touchdowns": Sequelize.INTEGER,
  "Return Yards": Sequelize.INTEGER,
  "Return Touchdowns": Sequelize.INTEGER,
  "2-Point Conversions": Sequelize.INTEGER,
  "Fumbles": Sequelize.INTEGER,
  "Fumbles Lost": Sequelize.INTEGER,
  "Field Goals 0-19 Yards": Sequelize.INTEGER,
  "Field Goals 20-29 Yards": Sequelize.INTEGER,
  "Field Goals 30-39 Yards": Sequelize.INTEGER,
  "Field Goals 40-49 Yards": Sequelize.INTEGER,
  "Field Goals 50+ Yards": Sequelize.INTEGER,
  "Field Goals Missed 0-19 Yards": Sequelize.INTEGER,
  "Field Goals Missed 20-29 Yards": Sequelize.INTEGER,
  "Field Goals Missed 30-39 Yards": Sequelize.INTEGER,
  "Field Goals Missed 40-49 Yards": Sequelize.INTEGER,
  "Field Goals Missed 50+ Yards": Sequelize.INTEGER,
  "Point After Attempt Made": Sequelize.INTEGER,
  "Point After Attempt Missed": Sequelize.INTEGER,
  "Points Allowed": Sequelize.INTEGER,
  "Sack": Sequelize.INTEGER,
  "Interception": Sequelize.INTEGER,
  "Fumble Recovery": Sequelize.INTEGER,
  "Touchdown": Sequelize.INTEGER,
  "Safety": Sequelize.INTEGER,
  "Block Kick": Sequelize.INTEGER,
  "Tackle Solo": Sequelize.INTEGER,
  "Tackle Assist": Sequelize.INTEGER,
  "Fumble Force": Sequelize.INTEGER,
  "Defensive Touchdown": Sequelize.INTEGER,
  "Pass Defended": Sequelize.INTEGER,
  "Kickoff and Punt Return Touchdowns": Sequelize.INTEGER,
  "Points Allowed 0 points": Sequelize.INTEGER,
  "Points Allowed 1-6 points": Sequelize.INTEGER,
  "Points Allowed 7-13 points": Sequelize.INTEGER,
  "Points Allowed 14-20 points": Sequelize.INTEGER,
  "Points Allowed 21-27 points": Sequelize.INTEGER,
  "Points Allowed 28-34 points": Sequelize.INTEGER,
  "Points Allowed 35+ points": Sequelize.INTEGER,
  "Offensive Fumble Return TD": Sequelize.INTEGER,
  "Pick Sixes Thrown": Sequelize.INTEGER,
  "40+ Yard Completions": Sequelize.INTEGER,
  "40+ Yard Passing Touchdowns": Sequelize.INTEGER,
  "40+ Yard Run": Sequelize.INTEGER,
  "40+ Yard Rushing Touchdowns": Sequelize.INTEGER,
  "40+ Yard Receptions": Sequelize.INTEGER,
  "40+ Yard Receiving Touchdowns": Sequelize.INTEGER,
  "Tackles for Loss": Sequelize.INTEGER,
  "Turnover Return Yards": Sequelize.INTEGER,
  "4th Down Stops": Sequelize.INTEGER,
  "Defensive Yards Allowed": Sequelize.INTEGER,
  "Defensive Yards Allowed - Negative": Sequelize.INTEGER,
  "Defensive Yards Allowed 0-99": Sequelize.INTEGER,
  "Defensive Yards Allowed 100-199": Sequelize.INTEGER,
  "Defensive Yards Allowed 200-299": Sequelize.INTEGER,
  "Defensive Yards Allowed 300-399": Sequelize.INTEGER,
  "Defensive Yards Allowed 400-499": Sequelize.INTEGER,
  "Defensive Yards Allowed 500+": Sequelize.INTEGER,
  "Three and Outs Forced": Sequelize.INTEGER,
  "Targets": Sequelize.INTEGER,
  "Passing 1st Downs": Sequelize.INTEGER,
  "Receiving 1st Downs": Sequelize.INTEGER,
  "Rushing 1st Downs": Sequelize.INTEGER,
  "Extra Point Returned": Sequelize.INTEGER,
}