module.exports = {
  "GameKey": "201510121",
  "SeasonType": 1,
  "Season": 2015,
  "Week": 1,
  "Date": "2015-09-10T20:30:00",
  "AwayTeam": "PIT",
  "HomeTeam": "NE",
  "Channel": "NBC",
  "PointSpread": 0,
  "OverUnder": 57.5,
  "StadiumID": 4,
  "GeoLat": 42.09,
  "GeoLong": -71.26,
  "ForecastTempLow": 61,
  "ForecastTempHigh": 72,
  "ForecastDescription": "Rain/Thunder",
  "ForecastWindChill": 65,
  "ForecastWindSpeed": 7,
  "AwayTeamMoneyLine": null,
  "HomeTeamMoneyLine": null,
  "StadiumDetails": {
    "StadiumID": 4,
    "Name": "Gillette Stadium",
    "City": "Foxborough",
    "State": "MA",
    "Country": "USA",
    "Capacity": 68756,
    "PlayingSurface": "Grass",
    "GeoLat": 42.090866,
    "GeoLong": -71.264244
  },
}