//stat at index 0 => Games Played, use for converting from 
//yahoo incoming data to our database field name

module.exports = [
  "Games Played",
  "Passing Attempts",
  "Completions",
  "Incomplete Passes",
  "Passing Yards",
  "Passing Touchdowns",
  "Interceptions",
  "Sacks",
  "Rushing Attempts",
  "Rushing Yards",
  "Rushing Touchdowns",
  "Receptions",
  "Receiving Yards",
  "Receiving Touchdowns",
  "Return Yards",
  "Return Touchdowns",
  "2-Point Conversions",
  "Fumbles",
  "Fumbles Lost",
  "Field Goals 0-19 Yards",
  "Field Goals 20-29 Yards",
  "Field Goals 30-39 Yards",
  "Field Goals 40-49 Yards",
  "Field Goals 50+ Yards",
  "Field Goals Missed 0-19 Yards",
  "Field Goals Missed 20-29 Yards",
  "Field Goals Missed 30-39 Yards",
  "Field Goals Missed 40-49 Yards",
  "Field Goals Missed 50+ Yards",
  "Point After Attempt Made",
  "Point After Attempt Missed",
  "Points Allowed",
  "Sack",
  "Interception",
  "Fumble Recovery",
  "Touchdown",
  "Safety",
  "Block Kick",
  "Tackle Solo",
  "Tackle Assist",
  "Fumble Force",
  "Defensive Touchdown",
  "Pass Defended",
  "Kickoff and Punt Return Touchdowns",
  "Points Allowed 0 points",
  "Points Allowed 1-6 points",
  "Points Allowed 7-13 points",
  "Points Allowed 14-20 points",
  "Points Allowed 21-27 points",
  "Points Allowed 28-34 points",
  "Points Allowed 35+ points",
  "Offensive Fumble Return TD",
  "Pick Sixes Thrown",
  "40+ Yard Completions",
  "40+ Yard Passing Touchdowns",
  "40+ Yard Run",
  "40+ Yard Rushing Touchdowns",
  "40+ Yard Receptions",
  "40+ Yard Receiving Touchdowns",
  "Tackles for Loss",
  "Turnover Return Yards",
  "4th Down Stops",
  "Defensive Yards Allowed",
  "Defensive Yards Allowed - Negative",
  "Defensive Yards Allowed 0-99",
  "Defensive Yards Allowed 100-199",
  "Defensive Yards Allowed 200-299",
  "Defensive Yards Allowed 300-399",
  "Defensive Yards Allowed 400-499",
  "Defensive Yards Allowed 500+",
  "Three and Outs Forced",
  "Targets",
  "Passing 1st Downs",
  "Receiving 1st Downs",
  "Rushing 1st Downs",
  "Extra Point Returned",
]