const stadiums =
  {
    'University of Phoenix Stadium': 'Glendale, AZ',
    'Georgia Dome': 'Atlanta, GA',
    'M&T Bank Stadium': 'Baltimore, MD',
    'Ralph Wilson Stadium': 'Orchard Park, NY',
    'Bank of America Stadium': 'Charlotte, NC',
    'Soldier Field': 'Chicago, IL',
    'Paul Brown Stadium': 'Cincinnati, OH',
    'FirstEnergy Stadium': 'Cleveland, OH',
    'AT&T Stadium': 'Arlington, TX',
    'Sports Authority Field at Mile High': 'Denver, CO',
    'Ford Field': 'Detroit, MI',
    'Lambeau Field': 'Green Bay, WI',
    'Reliant Stadium': 'Houston, TX',
    'Lucas Oil Stadium': 'Indianapolis, IN',
    'EverBank Field': 'Jacksonville, FL',
    'Arrowhead Stadium': 'Kansas City, MO',
    'Los Angeles Memorial Coliseum': 'Los Angeles, CA',
    'Sun Life Stadium': 'Miami Gardens, FL',
    'TCF Bank Stadium': 'Minneapolis, MN',
    'Gillette Stadium': 'Foxborough, MA',
    'Mercedes-Benz Superdome': 'New Orleans, LA',
    'MetLife Stadium': 'East Rutherford, NJ',
    'O.co Coliseum': 'Oakland, CA',
    'Lincoln Financial Field': 'Philadelphia, PA',
    'Heinz Field': 'Pittsburgh, PA',
    'Qualcomm Stadium': 'San Diego, CA',
    'CenturyLink Field': 'Seattle, WA',
    'Levi\'s Stadium': 'Santa Clara, CA',
    'Raymond James Stadium': 'Tampa Bay, FL',
    'LP Field': 'Nashville, TN',
    'FedEx Field': 'Landover, MD',
  };

export default stadiums;
