const teams = {
  ARI: 'Arizona',
  ATL: 'Atlanta',
  BAL: 'Baltimore',
  CAR: 'Carolina',
  BUF: 'Buffalo',
  CHI: 'Chicago',
  CIN: 'Cincinnati',
  CLE: 'Cleveland',
  DAL: 'Dallas',
  DEN: 'Denver',
  DET: 'Detroit',
  GB: 'Green Bay',
  HOU: 'Houston',
  IND: 'Indianapolis',
  JAX: 'Jacksonville',
  KC: 'Kansas City',
  LA: 'Los Angeles',
  MIA: 'Miami',
  NE: 'New England',
  NO: 'New Orleans',
  NYG: 'NY Giants',
  NYJ: 'NY Jets',
  OAK: 'Oakland',
  PHI: 'Philadelphia',
  MIN: 'Minnesota',
  PIT: 'Pittsburgh',
  SD: 'San Diego',
  SEA: 'Seattle',
  SF: 'San Francisco',
  TB: 'Tampa Bay',
  TEN: 'Tennessee',
  WAS: 'Washington',
};

export default teams;